(custom-set-variables
 '(require-final-newline nil)
 '(gutter-buffers-tab-visible-p t)
 '(paren-mode (quote blink-paren) nil (paren))
 '(text-mode-hook (quote (turn-on-auto-fill text-mode-hook-identify)) t)
 '(default-input-method "latin-1-prefix")
 '(speedbar-update-speed 1 t)
 '(browse-url-browser-function (quote browse-url-netscape))
 '(bar-cursor 2)
 '(case-fold-search t)
 '(global-font-lock-mode t nil (font-lock))
 '(show-paren-mode t nil (paren))
 '(printer-name "s3laser")
 '(toolbar-visible-p nil)
 '(truncate-lines t)
 '(c-basic-offset 2)
 '(current-language-environment "Latin-1")
 '(mouse-yank-at-point t)
 '(transient-mark-mode t)
 '(user-mail-address "madkins@qti.qualcomm.com")
 '(modeline-3d-p t)
 '(query-user-mail-address nil)
 '(font-lock-mode t nil (font-lock)))
(custom-set-faces
 '(default ((t (:size "12pt" :family "Courier" :background "cornsilk"))) t)
 '(cperl-nonoverridable-face ((((class color) (background light)) (:foreground "red3"))))
 '(font-lock-string-face ((((class color) (background light)) (:foreground "green4"))))
 '(cperl-hash-face ((((class color) (background light)) (:foreground "Purple"))))
 '(font-lock-variable-name-face ((((class color) (background light)) (:foreground "blue"))))
 '(font-lock-keyword-face ((t (:foreground "red4"))))
 '(blue ((t (:foreground "blue" :background ""))) t)
 '(font-lock-comment-face ((((class color) (background light)) (:foreground "orange4" :bold nil))))
 '(modeline ((t (:background "cornsilk"))) t)
 '(buffers-tab ((t (:background "cornsilk"))) t))

(setq minibuffer-max-depth nil)
